spring:
  application:
    name: bank
cloud:
  aws:
    credentials:
      access-key: localstack_access_key
      secret-key: localstack_secret_key
    region:
      static: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
    region: us-east-1